app/urls.py
"""1.(from django.urls import path) using this we r going to create different
sites & (from . import views) we need to import views.py file also bcz we need
to send the control from here to views.py file and as they r in the same folder
we r using from . import views
2.then we willl make urlpatterns to make paths
3.when it finds blank after main url of server it initially comes to url.py file
of the root folder ie facebook where when it finds and matches with the blank
which has an action of redirecting it to urls.py file of the app which then
matches with the particular url suppode for signup page (we want that while
loading the server we should directly come to signup page so on finding or
matching withe blank bcz after server url nothing is wriiten ie blank so we
need to redirect it to views.py file)redirects to signup page as it is going to
views.signup and similarly for the rest
suppose it is unable to match with any url it will display age not found""" 
from django.urls import path
from . import views

app_name = "app"


urlpatterns = [
path('',views.signup,name="signup"),
path('user_login/',views.user_login,name="login"),
path('user_logout/',views.user_logout,name="user_logout"),
path('home/<int:pk>/',views.home,name="home"),
path('makepost/<int:pk>',views.makepost,name="makepost"),
path('likepost/',views.likepost,name="likepost"),
path('comment/',views.comment,name="comment"),
path('profile/<int:pk>/<int:ppk>/',views.profile,name="profile"),
path('cover_pic_change/<int:pk>/',views.cover_pic_change,name="cover_pic_change"),
path('profile_pic_change/<int:pk>/',views.profile_pic_change , name="profile_pic_change"),
path('addbio/<int:pk>/',views.addbio,name="addbio"),
]

socialhub/urls.py
from django.contrib import admin
from django.urls import path , include
from . import settings
from django.contrib.staticfiles.urls import static
"""including the __init__.py file in ur folder helps you to know that
 project "app" is a python file or the python project  && if you
 import everything from app then no need to write(path('',views.home,))
 instead we can write the func name directly as path('',home,) """

""" whenever we type the url (127.0.0.1:8000) it will redirect it to urls.py
file of app (in utlpatterns 2nd path)"""


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

"""after doing this set up fro image_field is ready"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home</title>
    <link rel="stylesheet" href={% static 'css/home.css' %}>
    <script src="https://use.fontawesome.com/9ec2186b0f.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>
  <body>

    <header class="">
      <div class="logo-container">
        <div class="logo">
          <img src={% static 'images/fb.png' %} alt="">
        </div>
      </div>
      <div class="search-bar">
        <input type="text" name="" value="" placeholder="Search">
      </div>
      <div class="nav">
        <ul>
          <li>
            <a href="#"><i class="fa fa-home" aria-hidden="true"></i></a>
          </li>
          <li>
            <a href="#"><i class="fa fa-play" aria-hidden="true"></i></a>
          </li>
          <li>
            <a href="#"><i class="fa fa-users" aria-hidden="true"></i></a>
          </li>
        </ul>
      </div>
      <div class="profile">
        <div class="profile-pic">
          <img src="{{user_info.profile_pic.url}}" alt="">
        </div>
        <div class="username">
          <h3>{{user_info.user.first_name}}</h3>
        </div>
      </div>
    </header>

    <div class="menu">

      <ul>
        <li>
          <a href="{% url 'app:profile' user.id user.id %}"><i class="fa fa-user" aria-hidden="true"></i>Profile</a>
        </li>
        <li>
          <a href="{% url 'app:user_logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a>
        </li>
      </ul>

    </div>

    <section class="post-container">
<!--in make post the action part -this is a link of a particular user(user.id)-->
      <form class="make-post" method="post" enctype="multipart/form-data" action="{% url 'app:makepost' user.id %}">
        {% csrf_token %}
        <div class="post-text">
          <div class="profile-pic">
            <img src="{{user_info.profile_pic.url}}" alt="">
          </div>
          <div class="text">
            <input type="text" name="text" value="" placeholder="What's on your mind ?">
          </div>
        </div>



        <div class="post-visual">
          <ul>
            <li>
              <label for="image"><i class="fa fa-picture-o" aria-hidden="true"></i>Image</label>
              <input type="file" name="image" value="" id="image">
            </li>
            <li>
              <label for="video"><i class="fa fa-video-camera" aria-hidden="true"></i>Video</label>
              <input type="file" name="video" value="" id="video">
            </li>
          </ul>
        </div>
        <button type="submit" name="button">Post</button>

      </form>

<!--for each and every post(i) in all_posts which is a list-->
      {% for i in all_posts %}
      <div class="post ">
        <div class="post-maker">
          <div class="profile-pic">
            <!--providing the link or url to different different users profile_pic--> 
            <img src="{{i.user_info.profile_pic.url}}" alt="">
          </div>
          <h1>{{i.user.first_name}} {{i.user.last_name}}</h1>
        </div>
        <p>{{i.text}}</p>
        {% if i.image %}
        <div class="post-img">
          <img src="{{i.image.url}}" alt="">
        </div>
        {% endif %}
        {% if i.video %}
        <div class="post-video">
          <video src="{{i.video.url}}" controls>
          </video>
        </div>
        {% endif %}
        <div class="likes-comments" data-catid={{user.id}}>
          <div class="like" data-catid={{i.id}}>
              <i class="fa fa-thumbs-up" aria-hidden="true"></i><h5 id="like{{i.id}}">Like ({{i.l}})</h5>
          </div>
          <div class="comment">
            <form id="comment-form" method="post" enctype="multipart/form-data" data-catid={{i.id}}>
              {% csrf_token %}
              <input type="text" name="" value="" placeholder="Comment" id="comment{{i.id}}">
              <button type="submit" name="button">Post</button>
            </form>
          </div>
        </div>
        <span id="n-comment{{i.id}}">Comments ({{i.c}})</span>
        <div class="recent-comments" id="recent-comment{{i.id}}">
          {% for c in all_comments %}
            {% if forloop.parentloop.counter == forloop.counter %}
              {% for cmt in c %}
              <h4>{{cmt.user.first_name}} {{cmt.user.last_name}}</h4>
              <p>{{cmt.body}}</p>
              {% endfor %}
              {% endif %}
          {% endfor %}

        </div>
      </div>
    {% endfor %}



      <div class="user-list">

        <h2>Users</h2>

        {% for i in all_users %}
        <a href="{% url 'app:profile' user.id i.user.id %}" class="post-maker">
          <div class="profile-pic">
            <img src="{{i.profile_pic.url}}" alt="">
          </div>
          <h1>{{i.user.first_name}} {{i.user.last_name}}</h1>
        </a>
        {% endfor %}


      </div>

    </section>

  <script src={% static 'js/home.js' %} ></script>
  <script type="text/javascript">


    $(".like").click(function(){
      var catid,user;
      catid = $(this).attr("data-catid");
      user = $(".likes-comments").attr("data-catid");
      $.ajax(
        {
          url:"/likepost/",
          data:{
            post_id:catid,
            user_id:user,
          },
          success:function(data) {
            var id = "like" + catid;
            document.getElementById(id).innerHTML = "Likes(" + data +")";
          }
        }
      )
    })

    $(document).on('submit' , "#comment-form" , function(e){
      e.preventDefault();
      var catid,user,body;
      catid = $(this).attr('data-catid');
      user = $(".likes-comments").attr("data-catid");
      body = document.getElementById('comment'+catid).value;
      console.log(catid + " " + user + " "+ body);
      $.ajax(
        {
          url:"/comment",
          data:{
            post_id:catid,
            user_id:user,
            body:body,
          },
          success:function(data){
            document.getElementById("n-comment"+catid).innerHTML = "Comments(" + data[3] + ")";
            document.getElementById("recent-comment"+catid).innerHTML = "<h4>" + data[0]+" "+data[1] +"</h4><p>"+data[2]+"</p>" + document.getElementById("recent-comment"+catid).innerHTML;
            document.getElementById('comment'+catid).value = "";
          }
        }
      )


    })

  </script>
  </body>
</html>

app/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en",dir="ltr">
<head>
  <meta charset="utf-8">
	<title>Social Hub Signup or Login</title>
	<link rel="stylesheet" href={% static 'css/signup.css' %}>
</head>
<body>
	<header class="">
    <div class="logoname">
      <h1>Social Hub</h1>

    </div>
    <div class="login-form">
      <form class=""  method="post" enctype="multipart/form-data" action="{% url 'app:login' %}">
        {% csrf_token %}
        <div class="">

        </div>
        <div class="form">
          <span>Email</span>
          <input type="email" name="email" value="">
        </div>
        <div class="form">
          <span>Password</span>
          <input type="password" name="password" value="">

        </div>
        <div class="login-button">
          <button type="submit" name="button">Login</button>

        </div>
      </form>

    </div>
    <div class="">

    </div>

	</header>
  <section class="section1 ">
    <div class="">

    </div>
    <div class="registeration-form">
      <h1>Create a new account</h1>
      <p>It's quick and easy.</p>
      <form class="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="r-form1">
          <input type="text" name="first_name" value="" placeholder="First Name">
          <input type="text" name="last_name" value="" placeholder="Last Name" >
        </div>
        <div class="r-form2">
          <input type="email" name="email" value="" placeholder="Email">
          <input type="password" name="password" value="" placeholder="Password">
          <input type="date" name="birthday" value="" placeholder="Birthday">
          <input type="text" name="gender" value="" placeholder="Gender">
          <label for="image">Your image</label>
          <input type="file" name="image" value="" id="image">
          <p>By clicking Sign Up, you agree to our Terms, Data Policy and Cookie Policy. You may receive SMS notifications from us and can opt out at any time.</p>
          <button type="submit" name="button">Submit</button>
        </div>
      </form>

    </div>

  </section>
</body>
</html>